"""initial schema

Revision ID: 649209bb46a8
Revises: 
Create Date: 2026-09-09 16:40:04.661076

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '649209bb46a8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Required before any column can use the vector(n) type below.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=False),
    sa.Column('structured_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash')
    )
    op.create_index('uq_candidate_profiles_single_active', 'candidate_profiles', ['is_active'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('original_sheet_url', sa.String(length=2048), nullable=True),
    sa.Column('canonical_career_url', sa.String(length=2048), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name', name='uq_companies_normalized_name')
    )
    op.create_index(op.f('ix_companies_normalized_name'), 'companies', ['normalized_name'], unique=False)
    op.create_table('target_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('aliases', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('positive_keywords', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('negative_keywords', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('preferred_skills', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('max_expected_years', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name')
    )
    op.create_table('career_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('GREENHOUSE', 'LEVER', 'ASHBY', 'SMARTRECRUITERS', 'WORKABLE', 'COMEET', 'WORKDAY', 'TALEO', 'JSONLD', 'GENERIC_HTML', 'PLAYWRIGHT', 'UNSUPPORTED', name='career_source_type'), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('external_identifier', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('poll_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('last_successful_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_http_status', sa.Integer(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('unsupported_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'source_url', name='uq_career_sources_company_url')
    )
    op.create_index(op.f('ix_career_sources_company_id'), 'career_sources', ['company_id'], unique=False)
    op.create_index(op.f('ix_career_sources_next_check_at'), 'career_sources', ['next_check_at'], unique=False)
    op.create_table('crawl_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('career_source_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'PARTIAL', 'FAILED', name='crawl_run_status'), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('jobs_seen', sa.Integer(), nullable=False),
    sa.Column('jobs_created', sa.Integer(), nullable=False),
    sa.Column('jobs_updated', sa.Integer(), nullable=False),
    sa.Column('jobs_closed', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['career_source_id'], ['career_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_runs_career_source_id'), 'crawl_runs', ['career_source_id'], unique=False)
    op.create_index(op.f('ix_crawl_runs_status'), 'crawl_runs', ['status'], unique=False)
    op.create_table('job_postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('career_source_id', sa.Integer(), nullable=False),
    sa.Column('external_job_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('normalized_title', sa.String(length=500), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('team', sa.String(length=255), nullable=True),
    sa.Column('location_text', sa.String(length=500), nullable=True),
    sa.Column('normalized_location', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('remote_type', sa.Enum('ONSITE', 'HYBRID', 'REMOTE', 'UNKNOWN', name='remote_type'), nullable=False),
    sa.Column('employment_type', sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERNSHIP', 'TEMPORARY', 'UNKNOWN', name='employment_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('normalized_description', sa.Text(), nullable=True),
    sa.Column('responsibilities', sa.Text(), nullable=True),
    sa.Column('qualifications', sa.Text(), nullable=True),
    sa.Column('required_skills', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('preferred_skills', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('experience_min_years', sa.Integer(), nullable=True),
    sa.Column('experience_max_years', sa.Integer(), nullable=True),
    sa.Column('seniority', sa.Enum('INTERN', 'JUNIOR', 'MID', 'SENIOR', 'STAFF', 'PRINCIPAL', 'LEAD', 'MANAGER', 'DIRECTOR', 'UNKNOWN', name='seniority_level'), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('apply_url', sa.String(length=2048), nullable=True),
    sa.Column('source_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', 'UNKNOWN', name='job_status'), nullable=False),
    sa.Column('missing_streak', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['career_source_id'], ['career_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('career_source_id', 'external_job_id', name='uq_job_postings_source_external_id')
    )
    op.create_index('ix_job_postings_apply_url', 'job_postings', ['apply_url'], unique=False)
    op.create_index(op.f('ix_job_postings_career_source_id'), 'job_postings', ['career_source_id'], unique=False)
    op.create_index(op.f('ix_job_postings_company_id'), 'job_postings', ['company_id'], unique=False)
    op.create_index('ix_job_postings_embedding_hnsw', 'job_postings', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_job_postings_fingerprint', 'job_postings', ['company_id', 'normalized_title', 'normalized_location'], unique=False)
    op.create_index(op.f('ix_job_postings_normalized_title'), 'job_postings', ['normalized_title'], unique=False)
    op.create_index(op.f('ix_job_postings_status'), 'job_postings', ['status'], unique=False)
    op.create_table('job_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('INTERESTED', 'APPLIED', 'NOT_RELEVANT', 'TOO_SENIOR', 'WRONG_FIELD', 'WRONG_LOCATION', 'SAVED', 'REJECTED', name='job_feedback_action'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_feedback_job_id'), 'job_feedback', ['job_id'], unique=False)
    op.create_table('job_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_profile_id', sa.Integer(), nullable=False),
    sa.Column('target_role_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('candidate_semantic_score', sa.Float(), nullable=False),
    sa.Column('intent_semantic_score', sa.Float(), nullable=False),
    sa.Column('skill_score', sa.Float(), nullable=False),
    sa.Column('role_score', sa.Float(), nullable=False),
    sa.Column('seniority_score', sa.Float(), nullable=False),
    sa.Column('location_score', sa.Float(), nullable=False),
    sa.Column('recency_score', sa.Float(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('concerns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_role_id'], ['target_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_profile_id', 'target_role_id', 'job_id', name='uq_job_matches_profile_role_job')
    )
    op.create_index(op.f('ix_job_matches_candidate_profile_id'), 'job_matches', ['candidate_profile_id'], unique=False)
    op.create_index(op.f('ix_job_matches_final_score'), 'job_matches', ['final_score'], unique=False)
    op.create_index(op.f('ix_job_matches_job_id'), 'job_matches', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_matches_target_role_id'), 'job_matches', ['target_role_id'], unique=False)
    op.create_table('notification_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('candidate_profile_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('CONSOLE', 'WHATSAPP', name='notification_channel'), nullable=False),
    sa.Column('dedup_key', sa.String(length=255), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_key')
    )
    op.create_index(op.f('ix_notification_logs_job_id'), 'notification_logs', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_logs_job_id'), table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_index(op.f('ix_job_matches_target_role_id'), table_name='job_matches')
    op.drop_index(op.f('ix_job_matches_job_id'), table_name='job_matches')
    op.drop_index(op.f('ix_job_matches_final_score'), table_name='job_matches')
    op.drop_index(op.f('ix_job_matches_candidate_profile_id'), table_name='job_matches')
    op.drop_table('job_matches')
    op.drop_index(op.f('ix_job_feedback_job_id'), table_name='job_feedback')
    op.drop_table('job_feedback')
    op.drop_index(op.f('ix_job_postings_status'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_normalized_title'), table_name='job_postings')
    op.drop_index('ix_job_postings_fingerprint', table_name='job_postings')
    op.drop_index('ix_job_postings_embedding_hnsw', table_name='job_postings', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_job_postings_company_id'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_career_source_id'), table_name='job_postings')
    op.drop_index('ix_job_postings_apply_url', table_name='job_postings')
    op.drop_table('job_postings')
    op.drop_index(op.f('ix_crawl_runs_status'), table_name='crawl_runs')
    op.drop_index(op.f('ix_crawl_runs_career_source_id'), table_name='crawl_runs')
    op.drop_table('crawl_runs')
    op.drop_index(op.f('ix_career_sources_next_check_at'), table_name='career_sources')
    op.drop_index(op.f('ix_career_sources_company_id'), table_name='career_sources')
    op.drop_table('career_sources')
    op.drop_table('target_roles')
    op.drop_index(op.f('ix_companies_normalized_name'), table_name='companies')
    op.drop_table('companies')
    op.drop_index('uq_candidate_profiles_single_active', table_name='candidate_profiles', postgresql_where=sa.text('is_active'))
    op.drop_table('candidate_profiles')
    # ### end Alembic commands ###

    # drop_table doesn't drop the Postgres ENUM types the columns used;
    # without this, `downgrade base` followed by `upgrade head` fails with
    # 'type "career_source_type" already exists'.
    for enum_name in (
        "career_source_type",
        "crawl_run_status",
        "remote_type",
        "employment_type",
        "seniority_level",
        "job_status",
        "job_feedback_action",
        "notification_channel",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
