"""add job region and applications

Revision ID: 9d64d91cb390
Revises: b5caaa097bc3
Create Date: 2026-09-16 19:39:52.111145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d64d91cb390'
down_revision: Union[str, Sequence[str], None] = 'b5caaa097bc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('APPLIED', 'SCREENING', 'INTERVIEW', 'ASSIGNMENT', 'OFFER', 'REJECTED', 'WITHDRAWN', name='application_status'), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.add_column('job_postings', sa.Column('region', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_job_postings_region'), 'job_postings', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_postings_region'), table_name='job_postings')
    op.drop_column('job_postings', 'region')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
