"""add jobs_failed to crawl_runs

Revision ID: b5caaa097bc3
Revises: da3cb6356625
Create Date: 2026-09-15 15:50:59.973427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5caaa097bc3'
down_revision: Union[str, Sequence[str], None] = 'da3cb6356625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawl_runs', sa.Column('jobs_failed', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crawl_runs', 'jobs_failed')
    # ### end Alembic commands ###
