"""candidate profile processing status

Revision ID: f690f5712b6d
Revises: 9d64d91cb390
Create Date: 2026-09-16 20:12:38.717869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f690f5712b6d'
down_revision: Union[str, Sequence[str], None] = '9d64d91cb390'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('processing_status', sa.String(length=16), server_default='done', nullable=False))
    op.add_column('candidate_profiles', sa.Column('processing_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_profiles', 'processing_note')
    op.drop_column('candidate_profiles', 'processing_status')
    # ### end Alembic commands ###
